#
# AutoTweaker QQ Adapter
# Copyright (C) 2026  WhiteElephant-abc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m --enable-native-access=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=true
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2g --enable-native-access=ALL-UNNAMED
org.gradle.java.installations.auto-download=true
group=io.github.autotweaker
version=0.1.0
